matrix:
  include:
    - language: python
      python: "3.6"
      install: pip install -r backend/testing-requirements.txt codecov -e backend/ deepcolor/
      script: pytest --cov .

    - language: python
      python: "3.7"
      install: pip install -r backend/testing-requirements.txt codecov -e backend/ deepcolor/
      script: pytest --cov .

    - language: python
      python: "3.8"
      install: pip install -r backend/testing-requirements.txt codecov -e backend/ deepcolor/
      script: pytest --cov .
      after_success: codecov

    - language: generic
      services: docker
      script:
        - cd backend
        - docker build -t unstabletypes/image-backend:latest -f Dockerfile .
      deploy:
        provider: script
        script: bash docker_push.sh
        on:
          branch: master

    - language: node_js
      services: docker
      node_js: 13
      cache:
        directories:
          - node_modules
      before_install:
        - cd frontend
      script:
        - yarn install
        - yarn test

    - language: node_js
      node_js: "stable"
      cache:
        directories:
          - node_modules
      before_install:
        - cd frontend
      script:
        - yarn install
        - yarn test

    - language: generic
      services: docker
      before_install:
        - cd frontend
        - docker build -t unstabletypes/image-frontend:latest -f frontend.Dockerfile .
      deploy:
        provider: script
        script: bash docker_push.sh
        on:
          branch: master