matrix:
  include:
    - language: minimal
      services: docker
      script: docker build -f testing.Dockerfile --no-cache .

    - language: minimal
      services: docker
      script: docker build -f backend.Dockerfile .

    - language: node_js
      services: docker
      node_js: 13
      cache:
        directories:
          - node_modules
      before_install:
        - cd frontend
      script:
        - yarn install
        - yarn test

    - language: node_js
      node_js: "stable"
      cache:
        directories:
          - node_modules
      before_install:
        - cd frontend
      script:
        - yarn install
        - yarn test

    - language: minimal
      services: docker
      before_install:
        - cd frontend
        - docker build -t unstabletypes/image-frontend:latest -f frontend.Dockerfile .
      deploy:
        provider: script
        script: bash docker_push.sh
        on:
          branch: master