matrix:
  include:
    - language: python
      python: "3.6"
      install:
        - pip install --upgrade -r testing-requirements.txt codecov
        - pip install -e deepcolor/
        - pip install -e backend/
      script: pytest --cov .

    - language: python
      python: "3.7"
      install:
        - pip install --upgrade -r testing-requirements.txt codecov
        - pip install -e deepcolor/
        - pip install -e backend/
      script: pytest --cov .

    - language: python
      python: "3.8"
      install:
        - pip install --upgrade -r testing-requirements.txt codecov
        - pip install -e deepcolor/
        - pip install -e backend/
      script: pytest --cov .
      after_success: codecov

    - name: "Docker backend testing"
      language: minimal
      services: docker
      script: docker build -f testing.Dockerfile --no-cache .

    - name: "Docker backend build"
      language: minimal
      services: docker
      script: docker build -f backend.Dockerfile .

    - name: "Frontend Node.js 13"
      language: node_js
      services: docker
      node_js: 13
      cache:
        directories:
          - node_modules
      before_install:
        - cd frontend
      script:
        - yarn install
        - yarn test

    - name: "Frontend Node.js Stable"
      language: node_js
      node_js: "stable"
      cache:
        directories:
          - node_modules
      before_install:
        - cd frontend
      script:
        - yarn install
        - yarn test

    - name: "Docker frontend build"
      language: minimal
      services: docker
      before_install:
        - cd frontend
        - docker build -t unstabletypes/image-frontend:latest -f frontend.Dockerfile .
      deploy:
        provider: script
        script: bash docker_push.sh
        on:
          branch: master