version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: dev_nginx
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - dev-network
  frontend:
    image: unstabletypes/image-frontend:latest
    container_name: frontend_container
    expose:
      - "80"
    networks:
      - dev-network
networks:
  dev-network: