version: '3'
services:
  colornet:
    image: nginx:latest
    container_name: dev_nginx
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - dev-network
      - web
  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend.Dockerfile
    container_name: frontend_container
    expose:
      - "80"
    networks:
      - dev-network
  backend:
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
    networks:
      - dev-network
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

networks:
  web:
    external: true
  dev-network: