# Generated by Django 3.0.7 on 2020-06-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeepColorResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original", models.ImageField(upload_to="")),
                ("colored", models.ImageField(upload_to="")),
                ("method", models.CharField(max_length=20)),
            ],
        ),
    ]
